version: '3'
services: 
  desafio_mysql_db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 #para evitar problema com o mysql
    container_name: desafio2_mysqlDb    
    restart: always
    tty: true #faz o container ficar em execução em segundo plano
              #não esquecer de criar a pasta mysql no nível do docker-compose
    volumes: 
      - ./mysql:/var/lib/mysql #espelhar container a com a pasta mysql local
    environment: 
      - MYSQL_DATABASE=desafio_db_node #cria o banco     
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - desafio-dois-networks
networks: 
  desafio-dois-networks:
    driver: bridge

#docker-compose -f docker-compose-mysql.yaml up -d 
#acessar banco
#   docker logs desafio2_mysqlDb
#acessar banco
#   docker exec -it desafio2_mysqlDb bash
#   mysql -uroot -p
#   password: root    conforme definido nas váriaveis de ambiente
#   show databases;
#   use desafio_db_node
#     create table people  (id int not null auto_increment, name varchar(255), primary key(id));