FROM nginx
COPY ./default.conf /etc/nginx/conf.d/


#Entrar na pasta "nginx" para gerar a imagem "torrestor/nginxproxy"
#   docker build -t torrestor/nginxproxy .
#   docker images
#Executar o container "nginxproxy" com link no container "desafio2cnt_nodejsserver"
#   docker run -d -p 80:80 --link nodejsserver --name nginxproxy torrestor/nginxproxy
#       obs.: link nodejsserver => nome do container do node!