FROM node:14

WORKDIR /usr/src/app

COPY . .

#install client mysql

RUN npm install



#dependencia de container && apt-get install -y wget  
ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz



EXPOSE 8888

#CMD ["node", "index.js"]

#Entrar na pasta "node" para gerar a imagem "torrestor/nodejsapp"
#   docker build -t torrestor/nodejsapp .
#   docker images
#Executar o container nodejsserver
#   docker run -d -p 8888:8888 --name nodejsserver torrestor/nodejsapp
#Testar
#   http://localhost:8888
#Ver ip
#   ip addr
#       http://172.28.79.77:8888
#       172.19.207.193