FROM node:14

WORKDIR /usr/src/app

COPY ./package*.json /usr/src/app/

RUN npm install
COPY ./ /usr/src/app
EXPOSE 8888

CMD ["node", "index.js"]

#Entrar na pasta "node" para gerar a imagem "torrestor/nodejsapp"
#   docker build -t torrestor/nodejsapp .
#   docker images
#Executar o container nodejsserver
#   docker run -d -p 8888:8888 --name nodejsserver torrestor/nodejsapp
#Testar
#   http://localhost:8888
#Ver ip
#   ip addr
#       http://172.28.79.77:8888
#       172.19.207.193